function mark_nodes(nodes)
was_holded = ishold;
hold on

plot( ...
    nodes(:, 1), nodes(:, 2), ...
    "o", ...
    'LineStyle', 'none', ...
    'MarkerFaceColor', "red", ...
    "MarkerEdgeColor", "red" ...
    )

if ~was_holded
    hold off
end
end
