function mark_nodes(nodes)
was_holded = ishold;
hold on

plot( ...
    nodes(:, 1), nodes(:, 2), ...
    "o", ...
    'LineStyle', 'none', ...
    'MarkerFaceColor', "#999999", ...
    "MarkerEdgeColor", "#999999" ...
    )

if ~was_holded
    hold off
end
end
